<a href="https://colab.research.google.com/github/JLALLANOSM/Sis420_LlanosMendoza/blob/main/LabFinal/labFinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nombre: LLanos Mendoza Jose Luis Alberto

## Ing Sistemas 


In [422]:
# utilizado para la manipulación de directorios y rutas
import os

# Cálculo científico y vectorial para python
import numpy as np

# Libreria para graficos
from matplotlib import pyplot

# Modulo de optimizacion en scipy
from scipy import optimize

# modulo para cargar archivos en formato MATLAB
from scipy.io import loadmat

# le dice a matplotlib que incruste gráficos en el cuaderno
%matplotlib inline

In [423]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#la funcion csvAdapter, nos ayuda al tratamiento de datos, para cuantificar las caracteristicas del dataset

In [424]:
import pandas as pd

def csvAdapter(dataset,modificarColumnas,eliminarColumnas):
    data =pd.read_csv(dataset,encoding='latin-1')#lee y carga el archivo del data set a la variable data
    columna = data.columns #asignamos los nombres de columna a la variables columna

    for index in modificarColumnas:
        name = columna[index]
        value = list(data[name].unique())#obetenemos todos lo valores unicos de cada columna
        data[name] = data[name].map(dict(zip(value,[i for i in range(len(value))]))) #aqui es donde hacemos el tratamiento de datos donde a cada valor unico aiganmos un indice, indice que es numerico ejm 0=femenino, 1=masculino  
    data = data.drop([columna[index]for index in eliminarColumnas],axis=1)#eliminamos las columnas que no interesan en la resolucion o prediccion del problema   
    data = data.dropna()#eliminamos las filas que contengan valores nulos
    #data = pd.DataFrame(data, columns=columna)
    #dataN = data.to_numpy()
    print(data.head())
    return data
rutadataset='/content/drive/MyDrive/datasets/Train.csv'
columnaCategoricas = [i for i in range(0, 11) if not i in [3, 6, 8]]# poner columnas que no son categoricas o no interesan enla prediccionn
eliminarColumnas=[0]#columnas a eliminar
data = csvAdapter(rutadataset, columnaCategoricas, eliminarColumnas)

#from IPython import display

# ...

#data = csvAdapter(rutadataset, columnaCategoricas, eliminarColumnas)

# Convertir el array de NumPy a DataFrame

#data_df = pd.DataFrame(data, columns=columna)
# Guardar el nuevo dataset en un archivo CSV
#data_df.to_csv('nuevo_dataset.csv', index=False)

# Descargar el archivo CSV
#display.FileLink('nuevo_dataset.csv')


   Gender  Ever_Married  Age  Graduated  Profession  Work_Experience  \
0       0             0   22          0           0              1.0   
2       1             1   67          1           1              1.0   
3       0             1   67          1           2              0.0   
5       0             1   56          0           4              0.0   
6       0             0   32          1           0              1.0   

   Spending_Score  Family_Size  Var_1  Segmentation  
0               0          4.0      0             0  
2               0          1.0      1             2  
3               2          2.0      1             2  
5               1          2.0      1             3  
6               0          3.0      1             3  


In [425]:
#data[:,0].size

#la Funcion DatosSinteticos, nos ayuda a generar los datos sintetico mediante las funciones ramdom.choice que a partir de los datos del data set proporcionado va generando numeros aleatorios para cada columa tendiendo en cuenta como se dijo los datos de dataset

In [426]:
import pandas as pd
def DatosSinteticos(data):
    n_Filas = 10000
    datosNuevos = np.empty([n_Filas, len(data.columns)])#creamos una matriz vacia con 10000 fila y las cantidad de columnas existentes en el dataset
    
    for i in range(len(data.columns)):
        columna_i = data.iloc[:,i]
        muestras_i = np.random.choice(columna_i,n_Filas, replace=True)#generar los numeros aleatorio dependiendo de la muetra tomada, replace 
        datosNuevos[:,i] = muestras_i.round()#redondeamos las muestras para trabajar de mejor manera                           #replace indica si las muestras pueden o no repetirse 
    columnas = list(data.columns) #crea una lista de los nombres de columnas
    datosNuevos_df = pd.DataFrame(datosNuevos, columns=columnas) #crea un nuevo data frame 

    dataExtend = pd.concat([data, datosNuevos_df], axis=0)#concatena el data con los datos sinteticos creados
    print(dataExtend.tail())
    return dataExtend

data = DatosSinteticos(data)
#data.to_csv('nuevdata.csv')
data.size

      Gender  Ever_Married   Age  Graduated  Profession  Work_Experience  \
9995     0.0           0.0  67.0        1.0         0.0              6.0   
9996     1.0           1.0  28.0        1.0         4.0              0.0   
9997     1.0           1.0  61.0        0.0         4.0              4.0   
9998     0.0           0.0  65.0        0.0         0.0              9.0   
9999     1.0           1.0  19.0        0.0         4.0              8.0   

      Spending_Score  Family_Size  Var_1  Segmentation  
9995             1.0          1.0    1.0           3.0  
9996             1.0          9.0    1.0           2.0  
9997             2.0          2.0    1.0           0.0  
9998             2.0          1.0    1.0           0.0  
9999             0.0          3.0    1.0           3.0  


169690

In [440]:

#data = pd.read_csv('/content/drive/MyDrive/datasets/prediccionlluevia.csv', sep=',')
#data.head()
#value = list( data["PROFILE"].unique())
#print(len(value))
# Ingresar imágenes de dígitos de 20x20
input_layer_size  = 400

# 10 etiquetas, de 1 a 10 (tomar en cuenta que se asigna "0" a la etiqueta 10)
num_labels = 4

#  datos de entrenamiento almacenados en los arreglos X, y
#data = loadmat(os.path.join('/content/drive/MyDrive/datasets/prediccionlluevia.csv'))
#X, y = data['X'], data['y'].ravel()
# establecer el dígito cero en 0, en lugar del 10 asignado a este conjunto de datos
# Esto se hace debido a que el conjunto de datos se utilizó en MATLAB donde no hay índice 0
#y[y == 10] = 0
#___________________________________________________________________________________________________
#___________________________________________________________________________________________________
data = data.to_numpy()
#X, y = data[:, 0:9], data[:, 9]
#X, y = data[:3000, 0:9], data[:3000, 9] # para el 30 % de los datos 
X, y = data[:6000, 0:9], data[:6000, 9]# para el 60% de los datos 
#y =  y.round()
#print(y[7000])
m = y.size
m

AttributeError: ignored

In [428]:
print(X)
print(y)

[[ 0.  0. 22. ...  0.  4.  0.]
 [ 1.  1. 67. ...  0.  1.  1.]
 [ 0.  1. 67. ...  2.  2.  1.]
 ...
 [ 0.  1. 28. ...  0.  2.  1.]
 [ 1.  1. 35. ...  1.  2.  1.]
 [ 1.  1. 75. ...  2.  2.  1.]]
[0. 2. 2. ... 3. 3. 2.]


### 1.2 Visualización de los datos

Se comenzará visualizando un subconjunto del conjunto de entrenamiento. Se selecciona al azar, 100 filas de `X` y pasa esas filas a la función` displayData`. Esta función asigna cada fila a una imagen en escala de grises de 20 píxeles por 20 píxeles y muestra las imágenes juntas.

In [429]:
def displayData(X, example_width=None, figsize=(10, 10)):
    """
    Muestra datos 2D almacenados en X en una cuadrícula apropiada.
    """
    # Calcula filas, columnas
    if X.ndim == 2:
        m, n = X.shape
    elif X.ndim == 1:
        n = X.size
        m = 1
        X = X[None]  # Promocionar a una matriz bidimensional
    else:
        raise IndexError('La entrada X debe ser 1 o 2 dimensinal.')

    example_width = example_width or int(np.round(np.sqrt(n)))
    example_height = n / example_width

    # Calcula el numero de elementos a mostrar
    display_rows = int(np.floor(np.sqrt(m)))
    display_cols = int(np.ceil(m / display_rows))

    fig, ax_array = pyplot.subplots(display_rows, display_cols, figsize=figsize)
    fig.subplots_adjust(wspace=0.025, hspace=0.025)

    ax_array = [ax_array] if m == 1 else ax_array.ravel()

    for i, ax in enumerate(ax_array):
        ax.imshow(X[i].reshape(example_width, example_width, order='F'),
                  cmap='Greys', extent=[0, 1, 0, 1])
        ax.axis('off')

In [430]:
# Selecciona aleatoriamente 100 puntos de datos para mostrar
#rand_indices = np.random.choice(m, 100, replace=False)
#sel = X[rand_indices, :]

#displayData(sel)

In [431]:
# valores de prueba para los parámetros theta
theta_t = np.array([-2, -1, 1, 2], dtype=float)

# valores de prueba para las entradas
X_t = np.concatenate([np.ones((5, 1)), np.arange(1, 16).reshape(5, 3, order='F')/10.0], axis=1)
print(X_t)
# valores de testeo para las etiquetas
y_t = np.array([1, 0, 1, 0, 1])

# valores de testeo para el parametro de regularizacion
lambda_t = 3

[[1.  0.1 0.6 1.1]
 [1.  0.2 0.7 1.2]
 [1.  0.3 0.8 1.3]
 [1.  0.4 0.9 1.4]
 [1.  0.5 1.  1.5]]


In [432]:
def sigmoid(z):
    """
    Calcula la sigmoide de z.
    """
    return 1.0 / (1.0 + np.exp(-z))

In [433]:
def lrCostFunction(theta, X, y, lambda_):
    """
    Calcula el costo de usar theta como parámetro para la regresión logística regularizada y 
    el gradiente del costo w.r.t. a los parámetros.
    
    Parametros
    ----------
    theta : array_like
        Parametro theta de la regresion logistica. Vector de la forma(shape) (n, ). n es el numero de caracteristicas 
        incluida la intercepcion
        
    X : array_like
        Dataset con la forma(shape) (m x n). m es el numero de ejemplos, y n es el numero de 
        caracteristicas (incluida la intercepcion).
    
    y : array_like
        El conjunto de etiquetas. Un vector con la forma (shape) (m, ). m es el numero de ejemplos
    
    lambda_ : float
        Parametro de regularización. 
    
    Devuelve
    -------
    J : float
        El valor calculado para la funcion de costo regularizada. 
    
    grad : array_like
        Un vector de la forma (shape) (n, ) que es el gradiente de la 
        función de costo con respecto a theta, en los valores actuales de theta..
    """
    # Inicializa algunos valores utiles
    m = y.size
    epzilon = 1e-5 
    # convierte las etiquetas a valores enteros si son boleanos
    if y.dtype == bool:
        y = y.astype(int)
    
    J = 0
    grad = np.zeros(theta.shape)
    
    h = sigmoid(X.dot(theta.T))
    
    temp = theta
    temp[0] = 0
    
    J = (1 / m) * np.sum(-y.dot(np.log(h+epzilon)) - (1 - y).dot(np.log(1 - h+epzilon))) + (lambda_ / (2 * m)) * np.sum(np.square(temp))
    
    grad = (1 / m) * (h - y).dot(X) 
    grad = grad + (lambda_ / m) * temp

    return J, grad

In [434]:
J, grad = lrCostFunction(theta_t, X_t, y_t, lambda_t)

print('Costo         : {:.6f}'.format(J))
print('Costo esperadot: 2.534819')
print('-----------------------')
print('Gradientes:')
print(' [{:.6f}, {:.6f}, {:.6f}, {:.6f}]'.format(*grad))
print('Gradientes esperados:')
print(' [0.146561, -0.548558, 0.724722, 1.398003]');

Costo         : 2.534795
Costo esperadot: 2.534819
-----------------------
Gradientes:
 [0.146561, -0.548558, 0.724722, 1.398003]
Gradientes esperados:
 [0.146561, -0.548558, 0.724722, 1.398003]


<a id="section2"></a>
### 1.4 Clasificacion One-vs-all
En esta parte del ejercicio, se implementará la clasificación de uno contra todos mediante el entrenamiento de múltiples clasificadores de regresión logística regularizados, uno para cada una de las clases $K$ en nuestro conjunto de datos. En el conjunto de datos de dígitos escritos a mano, $K = 10$, pero su código debería funcionar para cualquier valor de $K$.

El argumento `y` de esta función es un vector de etiquetas de 0 a 9. Al entrenar el clasificador para la clase $k \in \{0, ..., K-1 \} $, querrá un vector K-dimensional de etiquetas $y$, donde $y_j \ in 0, 1$ indica si la instancia de entrenamiento $j ^ {th}$ pertenece a la clase $k$ $(y_j = 1)$, o si pertenece a una clase diferente $(y_j = 0)$.

Además, se utiliza `optimize.minimize` de scipy para este ejercicio.
<a id="oneVsAll"></a>

In [435]:
def oneVsAll(X, y, num_labels, lambda_):
    """
    Trains num_labels logistic regression classifiers and returns
    each of these classifiers in a matrix all_theta, where the i-th
    row of all_theta corresponds to the classifier for label i.
    
    Parameters
    ----------
    X : array_like
        The input dataset of shape (m x n). m is the number of 
        data points, and n is the number of features. Note that we 
        do not assume that the intercept term (or bias) is in X, however
        we provide the code below to add the bias term to X. 
    
    y : array_like
        The data labels. A vector of shape (m, ).
    
    num_labels : int
        Number of possible labels.
    
    lambda_ : float
        The logistic regularization parameter.
    
    Returns
    -------
    all_theta : array_like
        The trained parameters for logistic regression for each class.
        This is a matrix of shape (K x n+1) where K is number of classes
        (ie. `numlabels`) and n is number of features without the bias.
    """
    # algunas variables utiles
    m, n = X.shape
    
    all_theta = np.zeros((num_labels, n + 1))

    # Agrega unos a la matriz X
    X = np.concatenate([np.ones((m, 1)), X], axis=1)

    for c in np.arange(num_labels):
        initial_theta = np.zeros(n + 1)
        options = {'maxiter': 2000}
        res = optimize.minimize(lrCostFunction, 
                                initial_theta, 
                                (X, (y == c), lambda_), 
                                jac=True, 
                                method='CG',
                                options=options) 
        
        all_theta[c] = res.x

    return all_theta

In [441]:
lambda_ = 0.001 #modificamos para tratar de encontrar el mejor costo y las mejores thetas 
all_theta = oneVsAll(X, y, num_labels, lambda_)
print(all_theta.shape)
all_theta

(4, 10)


array([[ 1.99514796e+00, -3.92364165e-01, -5.57316711e-01,
        -3.59000193e-02, -1.16136854e+00, -1.17784992e-01,
         3.43044754e-02, -5.62388003e-01,  2.72638216e-02,
        -2.08136353e-02],
       [-6.88277066e-01, -1.16022737e-03,  8.51720351e-02,
         4.71258705e-03, -1.69311150e-01,  3.96831232e-02,
         2.29622743e-02, -3.00761646e-01, -2.26523729e-01,
        -1.82104761e-02],
       [-2.29008210e+00,  1.57928074e-01,  3.83358277e-01,
         9.76067671e-03,  3.30888096e-01,  5.02190798e-02,
        -2.25924306e-02,  1.37783824e-01, -3.51532027e-02,
         1.89760761e-02],
       [-3.90461477e+00,  1.82619942e-01,  4.49769003e-01,
         1.30842149e-02,  1.17871680e+00,  7.32746920e-02,
        -2.96344903e-02,  3.98304135e-01,  1.85812215e-01,
         8.16980342e-03]])

<a id="section3"></a>
#### 1.4.1 Prediccion One-vs-all

Después de entrenar el clasificador de one-vs-all, se puede usarlo para predecir el dígito contenido en una imagen determinada. Para cada entrada, debe calcular la "probabilidad" de que pertenezca a cada clase utilizando los clasificadores de regresión logística entrenados. La función de predicción one-vs-all seleccionará la clase para la cual el clasificador de regresión logística correspondiente genera la probabilidad más alta y devolverá la etiqueta de clase (0, 1, ..., K-1) como la predicción para el ejemplo de entrada.

In [437]:
def predictOneVsAll(all_theta, X):
    """
    Devuelve un vector de predicciones para cada ejemplo en la matriz X.
    Tenga en cuenta que X contiene los ejemplos en filas. 
    all_theta es una matriz donde la i-ésima fila es un vector theta de regresión logística entrenada para la i-ésima clase. 
    Debe establecer p en un vector de valores de 0..K-1 (por ejemplo, p = [0, 2, 0, 1] 
    predice clases 0, 2, 0, 1 para 4 ejemplos).
    
    Parametros
    ----------
    all_theta : array_like
        The trained parameters for logistic regression for each class.
        This is a matrix of shape (K x n+1) where K is number of classes
        and n is number of features without the bias.
    
    X : array_like
        Data points to predict their labels. This is a matrix of shape 
        (m x n) where m is number of data points to predict, and n is number 
        of features without the bias term. Note we add the bias term for X in 
        this function. 
    
    Devuelve
    -------
    p : array_like
        The predictions for each data point in X. This is a vector of shape (m, ).
    """
    
    m = X.shape[0];
    num_labels = all_theta.shape[0]

    p = np.zeros(m)

    # Add ones to the X data matrix
    X = np.concatenate([np.ones((m, 1)), X], axis=1)
    p = np.argmax(sigmoid(X.dot(all_theta.T)), axis = 1)

    return p

Una vez que haya terminado, se llama a la función `predictOneVsAll` usando el valor aprendido de $\theta$. Debería apreciarse que la precisión del conjunto de entrenamiento es de aproximadamente 95,1% (es decir, clasifica correctamente el 95,1% de los ejemplos del conjunto de entrenamiento).

In [438]:
print(X.shape)
pred = predictOneVsAll(all_theta, X)
print('Precision del conjuto de entrenamiento: {:.2f}%'.format(np.mean(pred == y) * 100))
XPrueba = X[5000:5001, :].copy()
print(XPrueba.shape)
#print(np.ones((1)))
print(XPrueba)
#p = np.zeros(1)
XPrueba = np.concatenate([np.ones((1, 1)), XPrueba], axis=1)
print(XPrueba.shape)
p = np.argmax(sigmoid(XPrueba.dot(all_theta.T)), axis = 1)
print('la clases p es= ',p)

#displayData(X[4002:4003, :])

(6000, 9)
Precision del conjuto de entrenamiento: 45.73%
(1, 9)
[[ 0.  2. 20.  0.  8.  3.  0.  2.  3.]]
(1, 10)
la clases p es=  [1]


array([[ 1.99514796e+00, -3.92364165e-01, -5.57316711e-01,
        -3.59000193e-02, -1.16136854e+00, -1.17784992e-01,
         3.43044754e-02, -5.62388003e-01,  2.72638216e-02,
        -2.08136353e-02],
       [-6.88277066e-01, -1.16022737e-03,  8.51720351e-02,
         4.71258705e-03, -1.69311150e-01,  3.96831232e-02,
         2.29622743e-02, -3.00761646e-01, -2.26523729e-01,
        -1.82104761e-02],
       [-2.29008210e+00,  1.57928074e-01,  3.83358277e-01,
         9.76067671e-03,  3.30888096e-01,  5.02190798e-02,
        -2.25924306e-02,  1.37783824e-01, -3.51532027e-02,
         1.89760761e-02],
       [-3.90461477e+00,  1.82619942e-01,  4.49769003e-01,
         1.30842149e-02,  1.17871680e+00,  7.32746920e-02,
        -2.96344903e-02,  3.98304135e-01,  1.85812215e-01,
         8.16980342e-03]])

Son las mejores thetas que se pudo encontrar para una corrida de 6000 muestras